//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseOperations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP_ProjectDBEntities : DbContext
    {
        public ERP_ProjectDBEntities()
            : base("name=ERP_ProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcity> tblcities { get; set; }
        public virtual DbSet<tblcourse_fees> tblcourse_fees { get; set; }
        public virtual DbSet<tblcourse_modules> tblcourse_modules { get; set; }
        public virtual DbSet<tbldesignation> tbldesignations { get; set; }
        public virtual DbSet<tblexam_level> tblexam_level { get; set; }
        public virtual DbSet<tblfee_modes> tblfee_modes { get; set; }
        public virtual DbSet<tblgender> tblgenders { get; set; }
        public virtual DbSet<tbllead_sources> tbllead_sources { get; set; }
        public virtual DbSet<tbllocation> tbllocations { get; set; }
        public virtual DbSet<tblmodule_topic> tblmodule_topic { get; set; }
        public virtual DbSet<tblqualification> tblqualifications { get; set; }
        public virtual DbSet<tblspecialization> tblspecializations { get; set; }
        public virtual DbSet<tblstate> tblstates { get; set; }
        public virtual DbSet<tbltechnology> tbltechnologies { get; set; }
        public virtual DbSet<tbltopiccontent> tbltopiccontents { get; set; }
        public virtual DbSet<tbltraining_modules> tbltraining_modules { get; set; }
        public virtual DbSet<tbltraining_topics> tbltraining_topics { get; set; }
        public virtual DbSet<tbltrainingcours> tbltrainingcourses { get; set; }
    }
}
