//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcity()
        {
            this.tbllocations = new HashSet<tbllocation>();
        }
    
        public int city_id { get; set; }
        public string city_name { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbllocation> tbllocations { get; set; }
        public virtual tblstate tblstate { get; set; }
    }
}
