//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfee_modes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblfee_modes()
        {
            this.tblcourse_fees = new HashSet<tblcourse_fees>();
        }
    
        public int fee_mode_id { get; set; }
        public string fee_mode { get; set; }
        public Nullable<int> flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcourse_fees> tblcourse_fees { get; set; }
    }
}
