//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllocation
    {
        public int location_id { get; set; }
        public string location_name { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual tblcity tblcity { get; set; }
    }
}
