//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblspecialization
    {
        public int specialization_id { get; set; }
        public string specialization_name { get; set; }
        public Nullable<int> qualification_id { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual tblqualification tblqualification { get; set; }
    }
}
