//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOpworks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERP_ProjectDBEntities : DbContext
    {
        public ERP_ProjectDBEntities()
            : base("name=ERP_ProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcenter_details> tblcenter_details { get; set; }
        public virtual DbSet<tblcity> tblcities { get; set; }
        public virtual DbSet<tblcourse_fees> tblcourse_fees { get; set; }
        public virtual DbSet<tblcourse_modules> tblcourse_modules { get; set; }
        public virtual DbSet<tbldesignation> tbldesignations { get; set; }
        public virtual DbSet<tblemployee_details> tblemployee_details { get; set; }
        public virtual DbSet<tblexam_level> tblexam_level { get; set; }
        public virtual DbSet<tblfee_modes> tblfee_modes { get; set; }
        public virtual DbSet<tblgender> tblgenders { get; set; }
        public virtual DbSet<tbllead_sources> tbllead_sources { get; set; }
        public virtual DbSet<tbllocation> tbllocations { get; set; }
        public virtual DbSet<tblmodule_topic> tblmodule_topic { get; set; }
        public virtual DbSet<tblqualification> tblqualifications { get; set; }
        public virtual DbSet<tblspecialization> tblspecializations { get; set; }
        public virtual DbSet<tblstate> tblstates { get; set; }
        public virtual DbSet<tblstudent_details> tblstudent_details { get; set; }
        public virtual DbSet<tblstudent_payment_details> tblstudent_payment_details { get; set; }
        public virtual DbSet<tblstudent_qualifications> tblstudent_qualifications { get; set; }
        public virtual DbSet<tblstudent_registration_details> tblstudent_registration_details { get; set; }
        public virtual DbSet<tbltechnology> tbltechnologies { get; set; }
        public virtual DbSet<tbltopiccontent> tbltopiccontents { get; set; }
        public virtual DbSet<tbltraining_modules> tbltraining_modules { get; set; }
        public virtual DbSet<tbltraining_topics> tbltraining_topics { get; set; }
        public virtual DbSet<tbltrainingcours> tbltrainingcourses { get; set; }
    
        public virtual ObjectResult<sp_fetch_tblcenter_details_Result> sp_fetch_tblcenter_details(Nullable<int> center_id)
        {
            var center_idParameter = center_id.HasValue ?
                new ObjectParameter("center_id", center_id) :
                new ObjectParameter("center_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblcenter_details_Result>("sp_fetch_tblcenter_details", center_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblcities_Result> sp_fetch_tblcities(Nullable<int> city_id)
        {
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblcities_Result>("sp_fetch_tblcities", city_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblcourse_fees_Result> sp_fetch_tblcourse_fees(Nullable<int> course_fee_id)
        {
            var course_fee_idParameter = course_fee_id.HasValue ?
                new ObjectParameter("course_fee_id", course_fee_id) :
                new ObjectParameter("course_fee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblcourse_fees_Result>("sp_fetch_tblcourse_fees", course_fee_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblcourse_modules_Result> sp_fetch_tblcourse_modules(Nullable<int> course_module_id)
        {
            var course_module_idParameter = course_module_id.HasValue ?
                new ObjectParameter("course_module_id", course_module_id) :
                new ObjectParameter("course_module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblcourse_modules_Result>("sp_fetch_tblcourse_modules", course_module_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbldesignations_Result> sp_fetch_tbldesignations(Nullable<int> designation_id)
        {
            var designation_idParameter = designation_id.HasValue ?
                new ObjectParameter("designation_id", designation_id) :
                new ObjectParameter("designation_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbldesignations_Result>("sp_fetch_tbldesignations", designation_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblemployee_details_Result> sp_fetch_tblemployee_details(Nullable<int> employee_id)
        {
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("employee_id", employee_id) :
                new ObjectParameter("employee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblemployee_details_Result>("sp_fetch_tblemployee_details", employee_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblexam_level_Result> sp_fetch_tblexam_level(Nullable<int> level_id)
        {
            var level_idParameter = level_id.HasValue ?
                new ObjectParameter("level_id", level_id) :
                new ObjectParameter("level_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblexam_level_Result>("sp_fetch_tblexam_level", level_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblfee_modes_Result> sp_fetch_tblfee_modes(Nullable<int> fee_mode_id)
        {
            var fee_mode_idParameter = fee_mode_id.HasValue ?
                new ObjectParameter("fee_mode_id", fee_mode_id) :
                new ObjectParameter("fee_mode_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblfee_modes_Result>("sp_fetch_tblfee_modes", fee_mode_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblgenders_Result> sp_fetch_tblgenders(Nullable<int> gender_id)
        {
            var gender_idParameter = gender_id.HasValue ?
                new ObjectParameter("gender_id", gender_id) :
                new ObjectParameter("gender_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblgenders_Result>("sp_fetch_tblgenders", gender_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbllead_sources_Result> sp_fetch_tbllead_sources(Nullable<int> source_id)
        {
            var source_idParameter = source_id.HasValue ?
                new ObjectParameter("source_id", source_id) :
                new ObjectParameter("source_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbllead_sources_Result>("sp_fetch_tbllead_sources", source_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbllocations_Result> sp_fetch_tbllocations(Nullable<int> location_id)
        {
            var location_idParameter = location_id.HasValue ?
                new ObjectParameter("location_id", location_id) :
                new ObjectParameter("location_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbllocations_Result>("sp_fetch_tbllocations", location_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblmodule_topic_Result> sp_fetch_tblmodule_topic(Nullable<int> module_topic_id)
        {
            var module_topic_idParameter = module_topic_id.HasValue ?
                new ObjectParameter("module_topic_id", module_topic_id) :
                new ObjectParameter("module_topic_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblmodule_topic_Result>("sp_fetch_tblmodule_topic", module_topic_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblqualifications_Result> sp_fetch_tblqualifications(Nullable<int> qualification_id)
        {
            var qualification_idParameter = qualification_id.HasValue ?
                new ObjectParameter("qualification_id", qualification_id) :
                new ObjectParameter("qualification_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblqualifications_Result>("sp_fetch_tblqualifications", qualification_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblspecializations_Result> sp_fetch_tblspecializations(Nullable<int> specialization_id)
        {
            var specialization_idParameter = specialization_id.HasValue ?
                new ObjectParameter("specialization_id", specialization_id) :
                new ObjectParameter("specialization_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblspecializations_Result>("sp_fetch_tblspecializations", specialization_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblstates_Result> sp_fetch_tblstates(Nullable<int> state_id)
        {
            var state_idParameter = state_id.HasValue ?
                new ObjectParameter("state_id", state_id) :
                new ObjectParameter("state_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblstates_Result>("sp_fetch_tblstates", state_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbltechnologies_Result> sp_fetch_tbltechnologies(Nullable<int> technology_Id)
        {
            var technology_IdParameter = technology_Id.HasValue ?
                new ObjectParameter("technology_Id", technology_Id) :
                new ObjectParameter("technology_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbltechnologies_Result>("sp_fetch_tbltechnologies", technology_IdParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbltopiccontents_Result> sp_fetch_tbltopiccontents(Nullable<int> content_id)
        {
            var content_idParameter = content_id.HasValue ?
                new ObjectParameter("content_id", content_id) :
                new ObjectParameter("content_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbltopiccontents_Result>("sp_fetch_tbltopiccontents", content_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbltraining_modules_Result> sp_fetch_tbltraining_modules(Nullable<int> module_id)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbltraining_modules_Result>("sp_fetch_tbltraining_modules", module_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbltraining_topics_Result> sp_fetch_tbltraining_topics(Nullable<int> topic_id)
        {
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbltraining_topics_Result>("sp_fetch_tbltraining_topics", topic_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbltrainingcourses_Result> sp_fetch_tbltrainingcourses(Nullable<int> course_id)
        {
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbltrainingcourses_Result>("sp_fetch_tbltrainingcourses", course_idParameter);
        }
    
        public virtual int sp_tblcenter_details(string type, Nullable<int> center_id, string center_code, string center_name, string center_type, string company_name, string gst_number, string address, string contact_number, string email_address, string password)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var center_idParameter = center_id.HasValue ?
                new ObjectParameter("center_id", center_id) :
                new ObjectParameter("center_id", typeof(int));
    
            var center_codeParameter = center_code != null ?
                new ObjectParameter("center_code", center_code) :
                new ObjectParameter("center_code", typeof(string));
    
            var center_nameParameter = center_name != null ?
                new ObjectParameter("center_name", center_name) :
                new ObjectParameter("center_name", typeof(string));
    
            var center_typeParameter = center_type != null ?
                new ObjectParameter("center_type", center_type) :
                new ObjectParameter("center_type", typeof(string));
    
            var company_nameParameter = company_name != null ?
                new ObjectParameter("company_name", company_name) :
                new ObjectParameter("company_name", typeof(string));
    
            var gst_numberParameter = gst_number != null ?
                new ObjectParameter("gst_number", gst_number) :
                new ObjectParameter("gst_number", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var contact_numberParameter = contact_number != null ?
                new ObjectParameter("contact_number", contact_number) :
                new ObjectParameter("contact_number", typeof(string));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblcenter_details", typeParameter, center_idParameter, center_codeParameter, center_nameParameter, center_typeParameter, company_nameParameter, gst_numberParameter, addressParameter, contact_numberParameter, email_addressParameter, passwordParameter);
        }
    
        public virtual int sp_tblcities(string type, Nullable<int> city_id, string city_name, Nullable<int> state_id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(int));
    
            var city_nameParameter = city_name != null ?
                new ObjectParameter("city_name", city_name) :
                new ObjectParameter("city_name", typeof(string));
    
            var state_idParameter = state_id.HasValue ?
                new ObjectParameter("state_id", state_id) :
                new ObjectParameter("state_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblcities", typeParameter, city_idParameter, city_nameParameter, state_idParameter);
        }
    
        public virtual int sp_tblcourse_fees(string type, Nullable<int> course_fee_id, Nullable<int> course_id, Nullable<int> fee_mode_id, Nullable<double> amount, Nullable<double> tax)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var course_fee_idParameter = course_fee_id.HasValue ?
                new ObjectParameter("course_fee_id", course_fee_id) :
                new ObjectParameter("course_fee_id", typeof(int));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            var fee_mode_idParameter = fee_mode_id.HasValue ?
                new ObjectParameter("fee_mode_id", fee_mode_id) :
                new ObjectParameter("fee_mode_id", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(double));
    
            var taxParameter = tax.HasValue ?
                new ObjectParameter("tax", tax) :
                new ObjectParameter("tax", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblcourse_fees", typeParameter, course_fee_idParameter, course_idParameter, fee_mode_idParameter, amountParameter, taxParameter);
        }
    
        public virtual int sp_tblcourse_modules(string type, Nullable<int> course_module_id, Nullable<int> course_id, Nullable<int> module_id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var course_module_idParameter = course_module_id.HasValue ?
                new ObjectParameter("course_module_id", course_module_id) :
                new ObjectParameter("course_module_id", typeof(int));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblcourse_modules", typeParameter, course_module_idParameter, course_idParameter, module_idParameter);
        }
    
        public virtual int sp_tbldesignations(string type, Nullable<int> designation_id, string designation_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var designation_idParameter = designation_id.HasValue ?
                new ObjectParameter("designation_id", designation_id) :
                new ObjectParameter("designation_id", typeof(int));
    
            var designation_nameParameter = designation_name != null ?
                new ObjectParameter("designation_name", designation_name) :
                new ObjectParameter("designation_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbldesignations", typeParameter, designation_idParameter, designation_nameParameter);
        }
    
        public virtual int sp_tblemployee_details(string type, Nullable<int> employee_id, string employee_code, string first_name, string middle_name, string last_name, Nullable<System.DateTime> birth_date, Nullable<System.DateTime> joining_date, string mobile_number, string email_address, string photo, Nullable<int> designation_id, Nullable<int> location_id, string permenant_address, string local_address, Nullable<int> center_id, string password)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("employee_id", employee_id) :
                new ObjectParameter("employee_id", typeof(int));
    
            var employee_codeParameter = employee_code != null ?
                new ObjectParameter("employee_code", employee_code) :
                new ObjectParameter("employee_code", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var birth_dateParameter = birth_date.HasValue ?
                new ObjectParameter("birth_date", birth_date) :
                new ObjectParameter("birth_date", typeof(System.DateTime));
    
            var joining_dateParameter = joining_date.HasValue ?
                new ObjectParameter("joining_date", joining_date) :
                new ObjectParameter("joining_date", typeof(System.DateTime));
    
            var mobile_numberParameter = mobile_number != null ?
                new ObjectParameter("mobile_number", mobile_number) :
                new ObjectParameter("mobile_number", typeof(string));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            var designation_idParameter = designation_id.HasValue ?
                new ObjectParameter("designation_id", designation_id) :
                new ObjectParameter("designation_id", typeof(int));
    
            var location_idParameter = location_id.HasValue ?
                new ObjectParameter("location_id", location_id) :
                new ObjectParameter("location_id", typeof(int));
    
            var permenant_addressParameter = permenant_address != null ?
                new ObjectParameter("permenant_address", permenant_address) :
                new ObjectParameter("permenant_address", typeof(string));
    
            var local_addressParameter = local_address != null ?
                new ObjectParameter("local_address", local_address) :
                new ObjectParameter("local_address", typeof(string));
    
            var center_idParameter = center_id.HasValue ?
                new ObjectParameter("center_id", center_id) :
                new ObjectParameter("center_id", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblemployee_details", typeParameter, employee_idParameter, employee_codeParameter, first_nameParameter, middle_nameParameter, last_nameParameter, birth_dateParameter, joining_dateParameter, mobile_numberParameter, email_addressParameter, photoParameter, designation_idParameter, location_idParameter, permenant_addressParameter, local_addressParameter, center_idParameter, passwordParameter);
        }
    
        public virtual int sp_tblexam_levels(string type, Nullable<int> level_id, string level_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var level_idParameter = level_id.HasValue ?
                new ObjectParameter("level_id", level_id) :
                new ObjectParameter("level_id", typeof(int));
    
            var level_nameParameter = level_name != null ?
                new ObjectParameter("level_name", level_name) :
                new ObjectParameter("level_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblexam_levels", typeParameter, level_idParameter, level_nameParameter);
        }
    
        public virtual int sp_tblfee_modes(string type, Nullable<int> fee_mode_id, string fee_mode)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var fee_mode_idParameter = fee_mode_id.HasValue ?
                new ObjectParameter("fee_mode_id", fee_mode_id) :
                new ObjectParameter("fee_mode_id", typeof(int));
    
            var fee_modeParameter = fee_mode != null ?
                new ObjectParameter("fee_mode", fee_mode) :
                new ObjectParameter("fee_mode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblfee_modes", typeParameter, fee_mode_idParameter, fee_modeParameter);
        }
    
        public virtual int sp_tblgenders(string type, Nullable<int> gender_id, string gender_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var gender_idParameter = gender_id.HasValue ?
                new ObjectParameter("gender_id", gender_id) :
                new ObjectParameter("gender_id", typeof(int));
    
            var gender_nameParameter = gender_name != null ?
                new ObjectParameter("gender_name", gender_name) :
                new ObjectParameter("gender_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblgenders", typeParameter, gender_idParameter, gender_nameParameter);
        }
    
        public virtual int sp_tbllead_sources(string type, Nullable<int> source_id, string source_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var source_idParameter = source_id.HasValue ?
                new ObjectParameter("source_id", source_id) :
                new ObjectParameter("source_id", typeof(int));
    
            var source_nameParameter = source_name != null ?
                new ObjectParameter("source_name", source_name) :
                new ObjectParameter("source_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbllead_sources", typeParameter, source_idParameter, source_nameParameter);
        }
    
        public virtual int sp_tbllocation(string type, Nullable<int> location_id, string location_name, Nullable<int> city_id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var location_idParameter = location_id.HasValue ?
                new ObjectParameter("location_id", location_id) :
                new ObjectParameter("location_id", typeof(int));
    
            var location_nameParameter = location_name != null ?
                new ObjectParameter("location_name", location_name) :
                new ObjectParameter("location_name", typeof(string));
    
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbllocation", typeParameter, location_idParameter, location_nameParameter, city_idParameter);
        }
    
        public virtual int sp_tblmodule_topic(string type, Nullable<int> module_topic_id, Nullable<int> module_id, Nullable<int> topic_id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var module_topic_idParameter = module_topic_id.HasValue ?
                new ObjectParameter("module_topic_id", module_topic_id) :
                new ObjectParameter("module_topic_id", typeof(int));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblmodule_topic", typeParameter, module_topic_idParameter, module_idParameter, topic_idParameter);
        }
    
        public virtual int sp_tblqualifications(string type, Nullable<int> qualification_id, string qualification_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var qualification_idParameter = qualification_id.HasValue ?
                new ObjectParameter("qualification_id", qualification_id) :
                new ObjectParameter("qualification_id", typeof(int));
    
            var qualification_nameParameter = qualification_name != null ?
                new ObjectParameter("qualification_name", qualification_name) :
                new ObjectParameter("qualification_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblqualifications", typeParameter, qualification_idParameter, qualification_nameParameter);
        }
    
        public virtual int sp_tblspecialization(string type, Nullable<int> specialization_id, string specialization_name, Nullable<int> qualification_id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var specialization_idParameter = specialization_id.HasValue ?
                new ObjectParameter("specialization_id", specialization_id) :
                new ObjectParameter("specialization_id", typeof(int));
    
            var specialization_nameParameter = specialization_name != null ?
                new ObjectParameter("specialization_name", specialization_name) :
                new ObjectParameter("specialization_name", typeof(string));
    
            var qualification_idParameter = qualification_id.HasValue ?
                new ObjectParameter("qualification_id", qualification_id) :
                new ObjectParameter("qualification_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblspecialization", typeParameter, specialization_idParameter, specialization_nameParameter, qualification_idParameter);
        }
    
        public virtual int sp_tblstates(string type, Nullable<int> state_id, string state_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var state_idParameter = state_id.HasValue ?
                new ObjectParameter("state_id", state_id) :
                new ObjectParameter("state_id", typeof(int));
    
            var state_nameParameter = state_name != null ?
                new ObjectParameter("state_name", state_name) :
                new ObjectParameter("state_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblstates", typeParameter, state_idParameter, state_nameParameter);
        }
    
        public virtual int sp_tbltechnologies(string type, Nullable<int> technology_id, string technology_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var technology_idParameter = technology_id.HasValue ?
                new ObjectParameter("technology_id", technology_id) :
                new ObjectParameter("technology_id", typeof(int));
    
            var technology_nameParameter = technology_name != null ?
                new ObjectParameter("technology_name", technology_name) :
                new ObjectParameter("technology_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbltechnologies", typeParameter, technology_idParameter, technology_nameParameter);
        }
    
        public virtual int sp_tbltopiccontent(string type, Nullable<int> content_id, string content_name, Nullable<int> topic_id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var content_idParameter = content_id.HasValue ?
                new ObjectParameter("content_id", content_id) :
                new ObjectParameter("content_id", typeof(int));
    
            var content_nameParameter = content_name != null ?
                new ObjectParameter("content_name", content_name) :
                new ObjectParameter("content_name", typeof(string));
    
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbltopiccontent", typeParameter, content_idParameter, content_nameParameter, topic_idParameter);
        }
    
        public virtual int sp_tbltraining_modules(string type, Nullable<int> module_id, string module_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            var module_nameParameter = module_name != null ?
                new ObjectParameter("module_name", module_name) :
                new ObjectParameter("module_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbltraining_modules", typeParameter, module_idParameter, module_nameParameter);
        }
    
        public virtual int sp_tbltrainingcourses(string type, Nullable<int> course_id, string course_name, string course_code, Nullable<int> technology_id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            var course_nameParameter = course_name != null ?
                new ObjectParameter("course_name", course_name) :
                new ObjectParameter("course_name", typeof(string));
    
            var course_codeParameter = course_code != null ?
                new ObjectParameter("course_code", course_code) :
                new ObjectParameter("course_code", typeof(string));
    
            var technology_idParameter = technology_id.HasValue ?
                new ObjectParameter("technology_id", technology_id) :
                new ObjectParameter("technology_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbltrainingcourses", typeParameter, course_idParameter, course_nameParameter, course_codeParameter, technology_idParameter);
        }
    
        public virtual int sp_trainingtopics(string type, Nullable<int> topic_id, string topic_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            var topic_nameParameter = topic_name != null ?
                new ObjectParameter("topic_name", topic_name) :
                new ObjectParameter("topic_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_trainingtopics", typeParameter, topic_idParameter, topic_nameParameter);
        }
    }
}
