//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOpworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcourse_fees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcourse_fees()
        {
            this.tblstudent_registration_details = new HashSet<tblstudent_registration_details>();
        }
    
        public int course_fee_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> fee_mode_id { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<int> flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblstudent_registration_details> tblstudent_registration_details { get; set; }
        public virtual tbltrainingcours tbltrainingcours { get; set; }
        public virtual tblfee_modes tblfee_modes { get; set; }
    }
}
