//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOpworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcenter_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcenter_details()
        {
            this.tblstudent_details = new HashSet<tblstudent_details>();
            this.tblemployee_details = new HashSet<tblemployee_details>();
        }
    
        public int center_id { get; set; }
        public string center_code { get; set; }
        public string center_name { get; set; }
        public string center_type { get; set; }
        public string company_name { get; set; }
        public string gst_number { get; set; }
        public string address { get; set; }
        public string contact_number { get; set; }
        public string email_address { get; set; }
        public string password { get; set; }
        public Nullable<int> flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblstudent_details> tblstudent_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblemployee_details> tblemployee_details { get; set; }
    }
}
