//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOpworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudent_payment_details
    {
        public int payment_id { get; set; }
        public Nullable<int> registration_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_for { get; set; }
        public Nullable<double> payment_amount { get; set; }
        public string payment_mode { get; set; }
        public string description { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual tblemployee_details tblemployee_details { get; set; }
        public virtual tblstudent_registration_details tblstudent_registration_details { get; set; }
    }
}
