//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOpworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblspecialization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblspecialization()
        {
            this.tblstudent_qualifications = new HashSet<tblstudent_qualifications>();
        }
    
        public int specialization_id { get; set; }
        public string specialization_name { get; set; }
        public Nullable<int> qualification_id { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual tblqualification tblqualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblstudent_qualifications> tblstudent_qualifications { get; set; }
    }
}
