//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOpworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudent_qualifications
    {
        public int student_qualification_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> specialization_id { get; set; }
        public string medium { get; set; }
        public Nullable<int> passing_year { get; set; }
        public Nullable<double> percentage { get; set; }
        public string university { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual tblspecialization tblspecialization { get; set; }
        public virtual tblstudent_details tblstudent_details { get; set; }
    }
}
