//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOpworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltrainingcours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbltrainingcours()
        {
            this.tblcourse_fees = new HashSet<tblcourse_fees>();
            this.tblcourse_modules = new HashSet<tblcourse_modules>();
            this.tblstudent_registration_details = new HashSet<tblstudent_registration_details>();
        }
    
        public int course_id { get; set; }
        public string course_name { get; set; }
        public string course_code { get; set; }
        public Nullable<int> technology_id { get; set; }
        public Nullable<int> flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcourse_fees> tblcourse_fees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcourse_modules> tblcourse_modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblstudent_registration_details> tblstudent_registration_details { get; set; }
        public virtual tbltechnology tbltechnology { get; set; }
    }
}
